name: task-api-ci

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  SPRING_DATA_MONGODB_URI: mongodb://localhost:27017/kaiburrdb

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:7
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --quiet --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Temurin JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: maven

      - name: Backend - Maven verify
        run: mvn -B clean package

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Frontend - Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Frontend - Lint
        run: npm run lint
        working-directory: frontend

      - name: Frontend - Build
        run: npm run build
        working-directory: frontend

      - name: Docker build
        run: docker build -t taskapi:${{ github.sha }} .
